Automation test for Password strengthening rules
LabKey/cds pull request #624
Opened 2024-01-03 17:52 UTC by labkey-sweta

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2024-01-09 18:27 UTC, labkey-tchad requested changes
Is it really necessary to make everything in `ChangePasswordDialog` refinding? We should be able to know when staleness happens and wait for it explicitly.

2024-01-09 18:27 UTC, labkey-tchad commented on test/src/org/labkey/test/components/cds/ChangePasswordDialog.java
> +    }
`submit` should wait for the dialog to disappear or go stale. There should be a separate `submitExpectingError` method for the error test cases to use.

2024-01-10 18:51 UTC, labkey-klum approved these changes

2024-01-24 20:59 UTC, labkey-tchad approved these changes
Looks good but failing on TeamCity

2024-01-26 07:00 UTC, merged